version: '3'
services:
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - ../data/db:/var/lib/mysql
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_USER: 'root'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
    php:
        build: php-apache
        ports:
            - 80:80
        volumes:
            - ./vhosts:/etc/apache2/sites-enabled
            - ../data/app:/var/www:z
        links:
            - db


